pipeline{
        agent any

        stages{
                stage('build'){
                        steps{
                          sh '''
                          echo "Building Docker image on  `hostname`"
                          docker image build -t app_image:1.0 ${WORKSPACE}/docker/
                          
                          '''
                        }
                 }
                 stage('test'){
                        steps{
                          sh '''
                          echo "Build is successful on test stage"
                          docker image ls 
                          '''
                        }
                 }

                  stage('deploy'){
                        steps{
                          sh '''
                          docker container run -d  --name c1 -p 9000:80 app_image:1.0
                          
                          echo "Build is successful on deploy stage `hostname`"
                          '''
                        }
                 }

                 stage('verify'){
                         steps{
                                 sh '''
                                        docker container ls 
                                 '''
                         }
                 }
          
        }

}
