pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
              sh '''
              echo " Build Docker image on `hostname`
              docker image build -t Skutty:1.0 ${WORKSPACE}/docker/Dockerfile
              '''
              
            }
        }
      
        stage('Test') {
            steps {
               sh '''
                echo "Test stage is successfull"
                docker image ls | grep Skutty
                '''
            }
        }
        stage('Deploy') {
            steps {
              sh '''
              docker container run -d --name c1 -p 9000:80 Skkutty:1.0
            
              echo "Build  is successfull on deploy stage `hostname`"
                '''
            }
        }
        stage('verify'){
            steps{
                sh ''' 
                    docker container ls | grep c1
                  '''
            }
   
        }
    }
}
