pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
              sh '''
              echo " Build Docker image on `hostname`
              docker image build -t Skutty:1.0
              
            }
        }
      
        stage('Test') {
            steps {
               sh 'echo "Test stage is successfull"
            }
        }
        stage('Deploy') {
            steps {
              sh '''
              bash ${WORKSPACE}/linux/script.sh
                echo "Build is successfull"
                '''
            }
        }
    }
}
